### ISSUE TITLE
OSError: exception: access violation writing 0x00000284C1557000

### ISSUE THREAD

**Issue by musakhawaja** [twardoch/audiostretchy#4]
hello, i keep getting this error when using audiostretchy for a wav to wav speedup. any help would be appreciated. I am running it on windows

code:
from audiostretchy.stretch import stretch_audio
stretch_audio("input.wav", "output.wav", ratio=1.1)

error:
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16828\3037458555.py in <module>
      1 from audiostretchy.stretch import stretch_audio
      2 
----> 3 stretch_audio("input.wav", "output.wav", ratio=1.1)

~\anaconda3\lib\site-packages\audiostretchy\stretch.py in stretch_audio(input_path, output_path, ratio, gap_ratio, upper_freq, lower_freq, buffer_ms, threshold_gap_db, double_range, fast_detection, normal_detection, sample_rate)
    354     audio_stretch = AudioStretch()
    355     audio_stretch.open(input_path)
--> 356     audio_stretch.stretch(
    357         ratio,
    358         gap_ratio,

~\anaconda3\lib\site-packages\audiostretchy\stretch.py in stretch(self, ratio, gap_ratio, upper_freq, lower_freq, buffer_ms, threshold_gap_db, double_range, fast_detection, normal_detection)
    314                 stretcher.output_capacity(self.nframes, ratio), dtype=np.int16
    315             )
--> 316             num_samples = stretcher.process_samples(
    317                 self.in_samples, len(self.in_samples), self.samples, ratio
    318             )

~\anaconda3\lib\site-packages\audiostretchy\interface\tdhs.py in process_samples(self, samples, num_samples, output, ratio)
    114         :return: The number of processed samples.
    115         """
--> 116         return self.stretch_samples(self.handle, samples, num_samples, output, ratio)
    117 
    118     def flush(self, output: np.ndarray) -> int:

OSError: exception: access violation writing 0x00000284C17F7000

**Comment by musakhawaja** [comment]
The code is running fine on a linux machine but the audio being produced has white noise after about 5 seconds, any suggestions on how to fix it?

**Comment by ducktailcat** [comment]
I'm getting a similar error on Windows 11

It's the same for wav and mp3 files using the stretch_audio() or the AudioStretch() method

 File "d:\Python\Pydub\main.py", line 3, in <module>
    stretch_audio("alabama-jam.wav", "output.wav", ratio=1.1)
  File "D:\Python\Pydub\venv-speed\lib\site-packages\audiostretchy\stretch.py", line 356, in stretch_audio
    audio_stretch.stretch(
  File "D:\Python\Pydub\venv-speed\lib\site-packages\audiostretchy\stretch.py", line 316, in stretch
    num_samples = stretcher.process_samples(
  File "D:\Python\Pydub\venv-speed\lib\site-packages\audiostretchy\interface\tdhs.py", line 116, in process_samples
    return self.stretch_samples(self.handle, samples, num_samples, output, ratio)
OSError: exception: access violation writing 0x00000156A6664000

**Comment by MASSKAgithub** [comment]
Will this bug be ever fixed? i have the exact same bug

Worked PERFECTLY first 3 minutes then this started to happen, rebooted PC, reinstalled the module, NOTHING HELPS wtf

**Comment by shawn-mek** [comment]
Same OSError. Would love a fix.

**Comment by niknah** [comment]
Are you guys using a stereo input?  It's working for me with mono but crashes with stereo.  

Fixed it up by adding `self.nchannels` in the lines below.  

audiostretchy/stretch.py:313

```
            self.samples = np.zeros(
                stretcher.output_capacity(self.nframes, ratio) * self.nchannels, dtype=np.int16
            )
            num_samples = stretcher.process_samples(
                self.in_samples, int( len(self.in_samples) / self.nchannels), self.samples, ratio
            )
```

There's a similar bit above this for `silence_mode` that may need changing too.

How do I compile _stretch.so, .dll, etc.?
